//go:build windows

package main

import (
	"encoding/binary"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

type runtimeTilesetJSON struct {
	ID                  int      `json:"id"`
	Name                string   `json:"name"`
	TilesetName         string   `json:"tileset_name"`
	AutotileNames       []string `json:"autotile_names"`
	SourceTilesetName   string   `json:"source_tileset_name,omitempty"`
	SourceAutotileNames []string `json:"source_autotile_names,omitempty"`
	Passages            []int    `json:"passages"`
	Priorities          []int    `json:"priorities"`
	TerrainTags         []int    `json:"terrain_tags"`
}

func rubyObjectInt(obj *rubyObject, key string) int {
	if obj == nil {
		return 0
	}
	switch v := obj.IVars[key].(type) {
	case int:
		return v
	case float64:
		return int(v)
	case string:
		i, _ := strconv.Atoi(strings.TrimSpace(v))
		return i
	default:
		return 0
	}
}

func rubyObjectString(obj *rubyObject, key string) string {
	if obj == nil {
		return ""
	}
	switch v := obj.IVars[key].(type) {
	case string:
		return v
	case nil:
		return ""
	default:
		return fmt.Sprint(v)
	}
}

func rubyObjectStringSlice(obj *rubyObject, key string) []string {
	if obj == nil {
		return []string{}
	}
	raw, ok := obj.IVars[key].([]any)
	if !ok {
		return []string{}
	}
	out := make([]string, 0, len(raw))
	for _, item := range raw {
		if item == nil {
			out = append(out, "")
			continue
		}
		out = append(out, fmt.Sprint(item))
	}
	return out
}

// Essentials/RGSS Table stores a 20-byte header followed by signed 16-bit
// cells. Passages/priorities/terrain tags are 1D Tables, so the runtime needs a
// flat array, not the generic diagnostic representation used by the importer.
func rubyTableFlatInts(value any) []int {
	u, ok := value.(*rubyUserData)
	if !ok || u == nil || !strings.EqualFold(u.Class, "Table") || len(u.Data) < 20 {
		return []int{}
	}
	xs := int(int32(binary.LittleEndian.Uint32(u.Data[4:8])))
	ys := int(int32(binary.LittleEndian.Uint32(u.Data[8:12])))
	zs := int(int32(binary.LittleEndian.Uint32(u.Data[12:16])))
	size := int(int32(binary.LittleEndian.Uint32(u.Data[16:20])))
	count := xs * maxIntImport(ys, 1) * maxIntImport(zs, 1)
	if size > 0 {
		count = size
	}
	available := (len(u.Data) - 20) / 2
	if count <= 0 || count > available {
		count = available
	}
	out := make([]int, count)
	off := 20
	for i := 0; i < count && off+2 <= len(u.Data); i++ {
		out[i] = int(int16(binary.LittleEndian.Uint16(u.Data[off : off+2])))
		off += 2
	}
	return out
}

func convertTilesetsForRuntime(sourceRX, destRoot string) (int, int, error) {
	value, err := decodeRubyMarshalFile(sourceRX)
	if err != nil {
		return 0, 0, err
	}
	rows, ok := value.([]any)
	if !ok {
		return 0, 0, fmt.Errorf("Tilesets.rxdata: struttura inattesa, atteso Array")
	}
	outDir := filepath.Join(destRoot, "converted", "tilesets")
	if err := os.MkdirAll(outDir, 0755); err != nil {
		return 0, 0, err
	}
	// Remove only aliases generated by a previous conversion. Original
	// Essentials graphics remain untouched in assets/Graphics.
	if err := cleanupGeneratedGraphicAliases(destRoot); err != nil {
		return 0, 0, err
	}

	// sourceRX is <Essentials>/Data/Tilesets.rxdata.  Numeric aliases are
	// generated from the original Graphics tree, while the untouched filenames
	// remain in assets/Graphics for scripts/events that still reference them.
	sourceRoot := filepath.Dir(filepath.Dir(sourceRX))
	aggregate := make([]any, len(rows))
	aliases := make([]plmAssetAliasEntry, 0)
	count := 0
	for index, row := range rows {
		if row == nil {
			aggregate[index] = nil
			continue
		}
		obj, ok := row.(*rubyObject)
		if !ok {
			return count, len(aliases), fmt.Errorf("Tilesets.rxdata indice %d: record non RPG::Tileset", index)
		}
		id := rubyObjectInt(obj, "id")
		if id <= 0 {
			id = index
		}
		if id <= 0 {
			aggregate[index] = nil
			continue
		}

		sourceTilesetName := rubyObjectString(obj, "tileset_name")
		sourceAutotileNames := rubyObjectStringSlice(obj, "autotile_names")
		canonicalTilesetName := ""
		if strings.TrimSpace(sourceTilesetName) != "" {
			canonicalTilesetName = fmt.Sprintf("%03d", id)
			alias, err := createNumericGraphicAlias(sourceRoot, destRoot, "Tilesets", sourceTilesetName, canonicalTilesetName, id, 0)
			if err != nil {
				return count, len(aliases), fmt.Errorf("tileset %d (%s): %w", id, sourceTilesetName, err)
			}
			aliases = append(aliases, alias)
		}

		canonicalAutotiles := make([]string, len(sourceAutotileNames))
		for slot, sourceName := range sourceAutotileNames {
			if strings.TrimSpace(sourceName) == "" {
				continue
			}
			canonical := fmt.Sprintf("%03d_%02d", id, slot+1)
			alias, err := createNumericGraphicAlias(sourceRoot, destRoot, "Autotiles", sourceName, canonical, id, slot+1)
			if err != nil {
				return count, len(aliases), fmt.Errorf("tileset %d autotile slot %d (%s): %w", id, slot+1, sourceName, err)
			}
			canonicalAutotiles[slot] = canonical
			aliases = append(aliases, alias)
		}

		entry := runtimeTilesetJSON{
			ID:                  id,
			Name:                rubyObjectString(obj, "name"),
			TilesetName:         canonicalTilesetName,
			AutotileNames:       canonicalAutotiles,
			SourceTilesetName:   sourceTilesetName,
			SourceAutotileNames: sourceAutotileNames,
			Passages:            rubyTableFlatInts(obj.IVars["passages"]),
			Priorities:          rubyTableFlatInts(obj.IVars["priorities"]),
			TerrainTags:         rubyTableFlatInts(obj.IVars["terrain_tags"]),
		}
		if entry.Name == "" {
			entry.Name = sourceTilesetName
		}
		if err := writeJSON(filepath.Join(outDir, fmt.Sprintf("%03d.json", id)), entry); err != nil {
			return count, len(aliases), err
		}
		aggregate[index] = entry
		count++
	}
	// The editor supports both per-ID files and an aggregate fallback. Keeping
	// this at converted/Tilesets.json also fixes the historical path mismatch
	// where the importer wrote only converted/data/Tilesets.json.
	if err := writeJSON(filepath.Join(destRoot, "converted", "Tilesets.json"), aggregate); err != nil {
		return count, len(aliases), err
	}
	if err := writeAssetAliasManifest(destRoot, aliases); err != nil {
		return count, len(aliases), err
	}
	return count, len(aliases), nil
}

func detectEssentialsProjectLanguage(rows []any) string {
	// Pokémon Essentials v20.1 uses English as its base catalog. Translated
	// projects keep the English ScriptTexts keys and replace their values.
	// Detect the two languages currently required by the PML compatibility
	// layer without using the Windows/system locale, which would change the
	// imported game's language.
	if len(rows) > 24 {
		if scripts, ok := rows[24].(map[string]any); ok {
			probes := map[string][]string{
				"Yes":        {"sì", "si"},
				"Cancel":     {"annulla"},
				"New Game":   {"nuova partita", "nuovo gioco"},
				"Your name?": {"il tuo nome?", "come ti chiami?"},
			}
			for key, italianValues := range probes {
				value, ok := scripts[key].(string)
				if !ok {
					continue
				}
				normalized := strings.ToLower(strings.TrimSpace(value))
				for _, italian := range italianValues {
					if normalized == italian {
						return "it"
					}
				}
			}
		}
	}
	return "en"
}

func convertMessagesForRuntime(sourceDAT, destRoot string) error {
	value, err := decodeRubyMarshalFile(sourceDAT)
	if err != nil {
		return err
	}
	converted := marshalToJSON(value)
	rows, ok := converted.([]any)
	if !ok {
		return fmt.Errorf("messages.dat: struttura inattesa, atteso Array")
	}
	payload := map[string]any{
		"format":            "pokemon-essentials-v20.1-messages",
		"source":            "messages.dat",
		"detected_language": detectEssentialsProjectLanguage(rows),
		"message_types":     rows,
	}
	return writeJSON(filepath.Join(destRoot, "converted", "messages.json"), payload)
}

type essentialsPreservedFile struct {
	SourcePath string `json:"source_path"`
	StoredPath string `json:"stored_path"`
	SHA256     string `json:"sha256"`
	Size       int64  `json:"size"`
}

type essentialsPreservationManifest struct {
	Schema string                    `json:"schema"`
	Files  []essentialsPreservedFile `json:"files"`
}

func preserveEssentialsSourceData(source, dest string) (int, error) {
	base := filepath.Join(dest, "converted", "source_essentials")
	dataSource := filepath.Join(source, "Data")
	dataDest := filepath.Join(base, "Data")
	if err := copyTree(dataSource, dataDest); err != nil {
		return 0, fmt.Errorf("snapshot Data: %w", err)
	}

	var files []essentialsPreservedFile
	addTree := func(srcRoot, storedRoot string) error {
		if !isDir(srcRoot) {
			return nil
		}
		return filepath.WalkDir(srcRoot, func(path string, d os.DirEntry, walkErr error) error {
			if walkErr != nil {
				return walkErr
			}
			if d.IsDir() {
				return nil
			}
			rel, err := filepath.Rel(srcRoot, path)
			if err != nil {
				return err
			}
			hash, err := sha256HexFile(path)
			if err != nil {
				return err
			}
			info, err := d.Info()
			if err != nil {
				return err
			}
			files = append(files, essentialsPreservedFile{
				SourcePath: filepath.ToSlash(filepath.Join(filepath.Base(srcRoot), rel)),
				StoredPath: filepath.ToSlash(filepath.Join(storedRoot, rel)),
				SHA256:     hash,
				Size:       info.Size(),
			})
			return nil
		})
	}
	if err := addTree(dataSource, "converted/source_essentials/Data"); err != nil {
		return 0, err
	}
	// PBS and Plugins are already copied to their canonical locations.  Record
	// those exact copies in the preservation manifest instead of duplicating the
	// same data a third time.
	if err := addTree(filepath.Join(source, "PBS"), "converted/PBS"); err != nil {
		return 0, err
	}
	if err := addTree(filepath.Join(source, "Plugins"), "converted/plugins_ruby"); err != nil {
		return 0, err
	}
	sort.Slice(files, func(i, j int) bool { return files[i].SourcePath < files[j].SourcePath })
	manifest := essentialsPreservationManifest{Schema: "plm.essentials_source_preservation.v1", Files: files}
	if err := writeJSON(filepath.Join(base, "manifest.json"), manifest); err != nil {
		return 0, err
	}
	return len(files), nil
}

func validatePreservedEssentialsSource(source, dest string) error {
	manifestPath := filepath.Join(dest, "converted", "source_essentials", "manifest.json")
	var manifest essentialsPreservationManifest
	b, err := os.ReadFile(manifestPath)
	if err != nil {
		return err
	}
	if err := jsonUnmarshalStrict(b, &manifest); err != nil {
		return err
	}
	for _, row := range manifest.Files {
		// StoredPath is always project-root relative. Keep one resolution rule so
		// the preservation manifest cannot silently point at a legacy/non-canonical
		// PBS location.
		stored := filepath.Join(dest, filepath.FromSlash(row.StoredPath))
		hash, err := sha256HexFile(stored)
		if err != nil {
			return fmt.Errorf("snapshot mancante %s: %w", row.StoredPath, err)
		}
		if !strings.EqualFold(hash, row.SHA256) {
			return fmt.Errorf("snapshot non identico: %s", row.StoredPath)
		}
	}
	return nil
}

func jsonUnmarshalStrict(data []byte, out any) error {
	// Kept as a small wrapper so source-preservation validation remains isolated
	// from UI code and can become stricter without changing call sites.
	return json.Unmarshal(data, out)
}
